services: 
  frontend:
    build: 
      context: ./frontend
    container_name: frontend
    restart: always
    ports:
      - '4200:80'
    networks:
      - mongo_network

  backend: 
    build: 
      context: ./backend
    container_name: backend
    restart: always
    ports:
      - '3000:3000'
    environment:
      DB_HOST: mongodb      
      DB_USER: fatou        
      DB_PASSWORD: root     
      DB_NAME: shoes_shop 
    networks:
      - mongo_network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports: 
      - '27017:27017'
    environment: 
      MONGO_INITDB_ROOT_USERNAME: fatou
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: shoes_shop
    volumes:
      - mongo_data:/data/db
    networks:
      - mongo_network

networks:
  mongo_network:
    driver: bridge

volumes:
  mongo_data:
    driver: local