services: 
  frontend:
    build: 
      context: ./frontend
    container_name: frontend
    restart: always
    ports:
      - '4200:80'
    volumes:
      - ./frontend:/app
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf 
    depends_on:
      - backend
    networks:
      - mongo_network

  backend: 
    build: 
      context: ./backend
    container_name: backend
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - mongo_network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports: 
      - '27017:27017'
    environment: 
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_ROOT_DATABASE}
    volumes:
      - mongo_data:/data/db
    networks:
      - mongo_network

networks:
  mongo_network:
    driver: bridge

volumes:
  mongo_data:
    driver: local